spring:
  application:
    name: spring-sinara-course
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    sql: debug
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
